### PR TITLE
Fixed bug: Refactoring from HashNormalize to Normalize was not appiel…

### PR DESCRIPTION
**Pull request by mattywausb**
Hi Jan, 
a recent fresh build of the component revealed a flaw in the begin javajet code, making the component unusable. I could not find out, why the 1.5 version was working with this bug. 
Greetings
MWG

### CODE REVIEW

**Comment by jlolling** [comment]
Thanks for the bug fix!

**Comment by jlolling** [comment]
I have just release the version 1.6 of this components on Github and will also update this component in Talend Exchange.
It turns out this bug must be exists only in the current code because in all of my projects the version 1.5 had no issues.

**Comment by jlolling** [comment]
I have also just updated the component in Talend Exchange. Talend must approve this update, can take a while.

**Comment by dakocddo** [comment]
Hi Jan, the error was caused by merging two supposedly identical versions of this component - your version and the one hosted at cimt-ag repository ... perhaps we should unite our versions into one again :)

**Comment by jlolling** [comment]
I suggest we use your repository because of the more active development. I would mirror your repo if possible.

**Pull request merged**
